# Frame list for "The Man Who Should Have Died" (Shanidar 1). One frame per timestamp.
STYLE = ("Medium-skill MS Paint sketch: a crude, rushed, hand-made doodle by someone with SOME drawing skill - amateur, funny, "
         "deliberately clumsy. Characters are simple cartoon stick-style people: round heads, simple bodies and limbs, a little more "
         "shape than pure stick figures. Plain pure white background with lots of empty space. Thick uneven wobbly shaky black outlines. "
         "Eyes as simple dots or plain circles, minimal facial expressions. Flat colour fills only, used sparingly (green, brown, grey, "
         "red, yellow, orange, blue). Red arrows or red question marks for emphasis. NO shading, NO gradients, NO 3D, NO cinematic "
         "lighting. NOT a polished cartoon, NOT Disney or anime look, not vector art, not professional. No detailed backgrounds or "
         "textures, no realistic people. Not gory. Uncluttered, subject centred with breathing room, nothing cropped. Wide horizontal "
         "YouTube video still. Any text is short handwritten scrawl, correctly spelled and legible.")
SHANIDAR = ("SHANIDAR MAN = a stick-figure Neanderthal with a thick heavy brow line, scruffy brown hair tuft, his left eye "
            "drawn as a small x, his right arm ending in a short stump below the elbow, leaning on a brown walking stick.")

P1 = [
("0:00", "A stick figure sitting on the ground clutching its leg, a red zigzag break mark on the shin, sweat drops, speech bubble \"OUCH!\". A crude white ambulance box with a red cross driving in from the right."),
("0:07", "A happy stick figure walking with a white cast on one leg, holding a small pill bottle. A calendar beside it reading \"6 WEEKS\" with a green checkmark."),
("0:15", "A stick caveman sitting on brown ground holding a leg with a red zigzag break. Above him three small icons crossed out with red X: a hospital with a red cross, a pill bottle, a fridge. Handwritten label \"50,000 YEARS AGO\"."),
("0:22", "A grey hillside. A hurt stick caveman sitting with a red blood drop on his leg. Two crude spotted brown hyenas on the right sniffing, with wavy red smell lines going from the blood drop to their noses."),
("0:30", "A white bone with a red zigzag crack, a red arrow pointing to a crude white skull. Nothing else."),
("0:35", "Tall jagged grey mountains with a dark cave opening. In front, a stick-figure archaeologist in a brown hat holding a shovel next to a small white skeleton lying in the dirt."),
("0:42", SHANIDAR + " He stands in the centre. Four red arrows point at him with short labels: \"EYE\", \"ARM\", \"LEG\", \"EARS\"."),
("0:47", SHANIDAR + " He stands next to a grey gravestone that is crossed out with a big red X. A few calendar pages fly around him."),
("0:54", "Three crude icons in a row, each crossed out with a red X: a grey stone hand axe, a wooden spear, an orange campfire."),
("1:00", "One big white bone in the centre with a smooth lump where it healed. A green checkmark and handwritten \"HEALED\"."),
("1:03", "A brown dirt cross-section with several small white skeletons lying in it. A big red question mark above."),
("1:08", "A stick-figure archaeologist holding a giant magnifying glass over brown ground full of scattered white bones."),
("1:11", "A crude green blob map of a small country with one red pin in it and handwritten label \"GEORGIA\"."),
("1:17", "A crude white skull with an empty mouth - almost no teeth. Handwritten label \"1.8 MILLION YRS\"."),
("1:26", "A stick figure shrugging next to a crude toothless white skull on a small table."),
("1:28", "A big crude lower jaw bone with smooth healed bone where the teeth were. Red arrows point at the smooth gum line. A small calendar with pages flying."),
("1:35", "A toothless stick figure grimacing at a red lump of raw meat and some brown tough roots. A small campfire icon crossed out with red X."),
("1:42", "One stick figure handing a bowl of mashed brown food to a toothless stick figure. Small red heart above them."),
("1:49", "A toothless stick figure sitting alone gumming a single red berry, with a shrug."),
("1:52", "A crude old white skull with a huge red question mark next to it."),
("1:56", "A green four-leaf clover and a white dice showing six dots."),
("1:58", "A stick figure pointing at a closed brown door with a red question mark on it."),
("2:01", "A crude yellow blob map with one red pin and handwritten label \"SPAIN\"."),
("2:02", "A stick-figure archaeologist looking through a magnifying glass at a tiny bone fragment shaped like a small snail-spiral."),
("2:09", "A big crude spiral inner-ear shape drawn in black with a red circle around it and handwritten label \"INNER EAR\"."),
("2:12", "A small stick-figure child standing a bit wobbly with little balance lines, smiling, next to a small cake with one candle and the number \"6\"."),
("2:20", "An adult stick figure carrying a small smiling stick child on its back through blue snowflakes, other stick figures walking alongside."),
("2:27", "A group of stick figures walking together with a small child in the middle holding an adult's hand. A green checkmark above."),
("2:30", "A crude green boot-shaped map of Italy with a red pin at the bottom and handwritten label \"11,000 YRS AGO\"."),
("2:36", "Two tall stick figures chasing a crude brown deer with spears in the distance, while a shorter stick figure with short arms and legs stands watching calmly."),
("2:41", "A brown dirt grave cross-section with two white skeletons lying together, one gently holding the other in its arms. A small red heart."),
("2:49", "A crude green blob map with a red pin and handwritten label \"VIETNAM\". Beside it a stick figure lying down on a mat."),
("2:55", "A stick figure kneeling and spoon-feeding another stick figure lying on a mat."),
("3:00", "A stick figure lying on a mat, next to a calendar reading \"10 YEARS\"."),
("3:05", "A crude grey wolf walking away from an injured wolf lying down, and a crude orange lion ignoring an old lion. Red X over both."),
("3:12", "A herd of crude brown deer running to the right, one deer left far behind limping. Two black birds circling above it."),
("3:17", "A green chalkboard with white handwritten text \"WEAK = LEFT BEHIND\"."),
("3:21", "The green chalkboard cracked in half by a big jagged line. A shovel beside it with handwritten \"1957\"."),
("3:29", "Tall jagged grey mountains with a small dark cave opening high on the side. Handwritten label \"IRAQ\"."),
("3:33", "Inside a grey cave, a stick-figure archaeologist in a brown hat digging with a shovel, piles of brown dirt beside him."),
("3:40", "Left: a dirt cross-section with layers and small bones. Right: a short stocky stick-figure Neanderthal with a heavy brow flexing next to a thin normal stick figure."),
("3:51", "A row of three small white skeletons, the middle one circled in red. Handwritten label \"SHANIDAR 1\"."),
("3:56", "A white skeleton lying on a table, a stick-figure scientist with a magnifying glass, red arrow pointing to the skull's face."),
("4:02", "A grey rock hitting the left side of a stick-figure head with a \"BONK\" and red crack lines around the eye."),
("4:07", "A big close-up of a stick-figure Neanderthal face with a heavy brow, the left eye drawn as an x and a red circle around it."),
("4:13", "A thin twisted arm bone ending at the elbow, with a dotted outline showing where the forearm and hand used to be. Red arrow."),
("4:20", "Two small panels with a red question mark between: left, a grey rock falling on an arm; right, a grey stone blade."),
("4:24", SHANIDAR + " He is doing a task one-handed, holding a stone tool in his left hand."),
("4:29", "A big white leg bone with an old red zigzag mark and small bumps at the ankle joint. Red arrows."),
("4:32", SHANIDAR + " He is limping, with red pain lines at his leg and a speech bubble \"OW\"."),
("4:38", "A crude ear shape with small grey bumps blocking the ear hole. Red arrows point at the bumps."),
("4:46", SHANIDAR + " Black sound-wave lines bounce off his ear, with a red X."),
("4:52", SHANIDAR + " He stands in the centre with blue snowflakes, surrounded at a distance by a crude cave lion, a brown bear, and a spotted hyena, all staring at him."),
("5:00", "A stick-figure scientist with a shocked open-O mouth and a red exclamation mark, looking at bones marked with green checkmarks."),
("5:06", "A big white bone with a thick healed lump, next to a calendar with many flying pages."),
("5:13", SHANIDAR + " He walks along a long wobbly path passing a yellow sun, then blue snowflakes, then a yellow sun again."),
("5:18", SHANIDAR + " He has a few grey hairs, next to a small cake with the number \"40\"."),
("5:22", SHANIDAR + " He is alone in a snowstorm of blue snowflakes with a huge red question mark above him."),
]
P2 = [
("0:00", SHANIDAR + " He sits alone on a rock while far away tiny stick figures chase a brown deer."),
("0:04", "A stocky stick-figure Neanderthal with an orange flame drawn in its belly, eating from a big pile of red meat. Handwritten label \"CALORIES\"."),
("0:08", "A crude spotted hyena licking its lips, staring at a limping stick figure that has a red target circle drawn on it."),
("0:13", "A group of stick figures carrying brown bundles, walking along a dotted path to the right."),
("0:18", "A dotted path winding over grey mountains, following a small herd of brown deer. A yellow sun on one side and blue snowflakes on the other."),
("0:24", SHANIDAR + " He is alone at the foot of a grey mountain with a red X beside him."),
("0:29", "One stick figure handing a red piece of meat to the Shanidar man, while another stick figure waits and looks back for him. " + SHANIDAR),
("0:34", "A stick figure holding a spear standing between a sitting Shanidar man and a black blob with yellow eyes. " + SHANIDAR),
("0:38", "A calendar full of tick marks, and a small pile of food being split between a group of stick figures."),
("0:45", "A stick-figure scientist in a white coat raising one finger with a speech bubble \"CAREFUL\"."),
("0:48", "A white skeleton with a red heart outline over its chest and a red question mark. A magnifying glass."),
("0:51", SHANIDAR + " A yellow light bulb above his head."),
("0:54", SHANIDAR + " He points at a crude map with a blue water drop, brown animal arrows, and a grey stone tool."),
("0:59", "Two stick figures shaking hands, a red heart crossed out beside them."),
("1:02", "The stick-figure scientist in the white coat with a small shrug and a green checkmark."),
("1:04", "A big red arrow pointing right with a magnifying glass at its tip."),
("1:08", "A crude balance scale: one side labelled \"ALIVE\" is heavier than the side labelled \"DEAD\". A group of stick figures watches."),
("1:14", "Two stick figures carrying the Shanidar man on a stretcher made of brown sticks. " + SHANIDAR),
("1:19", "A long row of small repeating panels, each with stick figures carrying another stick figure, a red arrow underneath going right."),
("1:23", "A crude lion, wolf and bird each with a red question mark, staring at stick figures carrying an injured one."),
("1:27", "An old brown book lying open with a red question mark above it."),
("1:30", "A stick-figure woman with glasses standing at a small podium, another stick figure asking with a speech bubble \"?\"."),
("1:35", "A big white thigh bone with a healed lump in the middle and a green checkmark."),
("1:39", "Left: a crude brown deer lying with a broken leg, red X. Right: a stick figure helping another stick figure with a splinted leg walk, green checkmark."),
("1:46", "A stick figure raising one finger, a small exclamation mark above."),
("1:47", "An empty grey filing cabinet drawer with a blank paper and a red X."),
("1:50", "A big red rubber-stamp style handwritten word \"MYTH?\"."),
("1:52", "White bones lying in brown dirt with a speech bubble coming from them."),
("1:56", "A white skeleton with its healed eye socket, arm and leg circled in green."),
("1:58", "A crude world map of lumpy green blobs with four red pins on it."),
("2:03", "A stick figure pointing at a group of stick figures standing together."),
("2:06", "A muscly stick caveman flexing proudly on a small podium, a thin stick figure left behind with a red X."),
("2:13", "A giant magnifying glass over a pile of white bones."),
("2:15", "Left: a group walking together including one on crutches, green check. Right: a group walking away from one sitting alone, red X."),
("2:19", "An old toothless stick figure pointing to a small blue water hole hidden between rocks. Dry cracked brown ground and a hot yellow sun."),
("2:25", "The Shanidar man sitting and teaching two small stick children, pointing at footprints in the dirt and a stone tool. " + SHANIDAR),
("2:32", "A group of stick figures carrying one injured stick figure, each with a small yellow light bulb above its head."),
("2:35", "A group of stick figures walking away, their light bulbs turning grey and falling off one by one."),
("2:39", "A brown bookshelf where each 'book' is a stick figure standing on the shelf."),
("2:43", "A single brown book burning with orange flames."),
("2:46", "A timeline arrow with \"SURVIVAL\" then \"KINDNESS\", with a red X over the arrow."),
("2:50", "A comfy orange armchair with a small red heart floating above it."),
("2:53", "A circle of stick figures holding hands with a big red heart in the middle."),
("2:56", "A modern stick figure pointing straight out at the viewer."),
("2:58", "A modern stick figure standing with arms crossed, wearing black sunglasses, looking confident."),
("3:00", "A modern stick figure holding a wallet and a wrench, with a speech bubble \"I'M FINE\"."),
("3:05", "An adult stick figure carrying a small baby in its arms."),
("3:10", "A small stick baby lying in a brown crib with a milk bottle."),
("3:15", "Left: a stick baby lying helpless. Right: a crude brown baby horse already standing up. A red question mark between."),
("3:17", "An adult stick figure holding a baby by a crib at night, yellow crescent moon in the window."),
("3:23", SHANIDAR + " A crossed-out handwritten word \"EXCEPTION\" above him."),
("3:27", SHANIDAR + " He holds up a yellow ruler, handwritten label \"THE RULE\"."),
("3:28", "A row of stick figures holding hands, going from a caveman on the left to a modern person on the right."),
("3:30", "Left: a lone stick figure with a red X. Right: a group of stick figures together with a green checkmark."),
("3:34", "A modern stick figure sitting sadly on a couch with a thought bubble showing a small cave with the Shanidar man inside."),
("3:38", SHANIDAR + " Close portrait of him with three red arrows pointing at his eye, arm and ear."),
("3:41", "A stick figure placing a hand on the Shanidar man's shoulder, a small red heart above. " + SHANIDAR),
("3:44", "A stick figure pointing at a big red heart with handwritten \"OLDEST\"."),
("3:46", "A timeline arrow: on the right a grey city icon and a yellow wheat icon, far on the left a red heart."),
("3:52", "A wooden spear and an orange campfire, both crossed out with red X."),
("3:54", "A group of stick figures walking away in the distance while one stick figure sits beside an injured one, staying."),
("3:56", "The Shanidar man with a stick-figure friend helping him walk, handwritten label \"50,000 YRS\". " + SHANIDAR),
("4:00", "A big red question mark and a small stick figure with a shocked open mouth."),
("4:03", "A grey cave. In front, a small smiling stick child standing with one leg and a brown crutch, a grey stone blade nearby, a green checkmark. Handwritten label \"31,000 YRS AGO\"."),
("4:11", "A big crude red rounded rectangle button with white handwritten text \"SUBSCRIBE\". A stick figure next to it holding a small grey stone knife, waving."),
]
