# One frame per 5-second timestamp for "Solving a 430,000-Year-Old Murder".
STYLE = ("Medium-skill MS Paint sketch: a crude hand-made doodle by someone with some drawing skill - amateur, funny, "
         "deliberately clumsy. Characters are simple cartoon stick-style people with round heads and simple bodies, eyes as "
         "plain dots or circles, and clear simple facial expressions. Thick uneven hand-drawn black outlines. Flat colour fills "
         "only (green, brown, grey, red, yellow, orange, blue). The whole frame is filled with NO empty white space: a simple "
         "flat-coloured background built from primitive shapes (cave walls, rocks, ground, sky, room walls, shelves) with a few "
         "simple background details, but no complex textures. Red arrows or red question marks for emphasis. NO shading, NO "
         "gradients, NO 3D, NO cinematic lighting. NOT a polished cartoon, NOT Disney or anime look, not vector art, not "
         "professional, no realistic people. Not gory, no blood. Uncluttered, subject centred with breathing room, nothing "
         "cropped. Wide horizontal 16:9 YouTube video still. Any text is short handwritten scrawl, correctly spelled and legible.")
DET = "The DETECTIVE is a cartoon stick-style man in a brown trench coat and brown hat, holding a magnifying glass."
NEA = "Early cavemen are stocky cartoon figures with heavy brows, scruffy brown hair and brown fur wraps."
SHA = ("The SHANIDAR MAN is a cartoon Neanderthal with a heavy brow, scruffy brown hair, his left eye drawn as a small x, "
       "his right arm ending in a short stump, leaning on a brown walking stick.")

SCENES = [
("0:00", DET+" He arrives at a dark cave entrance in a brown hillside, yellow police tape across it, looking surprised."),
("0:05", DET+" He shrugs inside a grey cave over an empty dirt floor. Three small icons crossed out in red: a fingerprint, an eye, a person silhouette."),
("0:10", DET+" He looks shocked at a wooden table holding a white skull broken into many pieces. Handwritten label \"52 PIECES\"."),
("0:15", DET+" He scratches his head next to a wooden sign reading \"430,000 YEARS AGO\". Big red question mark."),
("0:20", "A lab with grey walls and shelves. Two cartoon scientists in white coats gluing white skull pieces together on a table."),
("0:25", "A lab with a microscope and a boxy computer screen showing a skull outline. A scientist holding a clipboard, focused."),
("0:30", NEA+" Two cavemen face each other in a cave, one angrily raising a wooden club, the other scared. A red exclamation mark."),
("0:35", DET+" He stands at a cork board pinned with little drawings of a skull, a club and question marks connected by red string."),
("0:40", "Close-up of the cork board: a drawing of a deep pit with a body shape at the bottom and a red question mark. The detective's hand points at it."),
("0:45", DET+" He holds a brown folder labelled \"CASE FILE\" and points toward a dark cave entrance."),
("0:50", "A spooky dark cave mouth in a grey rocky hillside at dusk, a few black bats, orange sky."),
("0:55", "Green rolling hills under a blue sky with a few trees, a small red map pin and a wooden sign \"SPAIN\"."),
("1:00", DET+" He crawls on hands and knees through a narrow grey rock tunnel, wearing a small headlamp, looking nervous."),
("1:05", DET+" He stands at the edge where the tunnel floor ends in a black hole, arms flailing, shocked face."),
("1:10", "Side cross-section of grey rock: a tall narrow vertical shaft next to a small four-storey building drawn for scale. Label \"13 M\"."),
("1:15", "A dark brown underground chamber at the bottom of the shaft, rope hanging down, a wooden sign \"SIMA DE LOS HUESOS\"."),
("1:20", "Two cartoon researchers with helmets and shovels climbing down a rope ladder into the chamber, a sign \"PIT OF BONES\"."),
("1:25", "The chamber floor packed with white bones. The two researchers stare with wide shocked eyes and open mouths."),
("1:30", "A lab table covered in rows of small white bone pieces. A scientist with a counter sign \"28 PEOPLE\"."),
("1:35", NEA+" A cramped small underground chamber holding a group of men, women and teenagers drawn as simple outlines, squeezed together, looking worried."),
("1:40", "Side by side: a modern cartoon person and a stocky early caveman with a heavy brow. A red not-equal sign between them."),
("1:45", "A lab bench, a scientist with a pipette and test tubes, a screen showing a blue and red DNA double helix."),
("1:50", "A big DNA double helix with a gold star and handwritten \"OLDEST DNA\". A scientist cheering."),
("1:55", "A big teardrop-shaped stone hand axe coloured reddish-pink, with small sparkle marks, resting on a grey rock ledge in the cave."),
("2:00", "A grey cave interior with grey rocks; the pink stone axe stands out with a red arrow pointing out of the cave to distant hills."),
("2:05", "The pink hand axe lying among white bones on the cave floor, a wooden sign \"EXCALIBUR\"."),
("2:10", DET+" He opens the CASE FILE folder; three icons float above: a pit, a group of 28 tiny figures, one axe."),
("2:15", "A white skull on a wooden stand with a paper tag \"CRANIUM 17\", in a room with a shelf of boxes."),
("2:20", "Cartoon archaeologists digging in the dark chamber, a bucket of small skull fragments, a calendar with pages flying."),
("2:25", "A scientist fitting jigsaw-puzzle-shaped white skull pieces together on a table, tongue out in concentration."),
("2:30", "A finished white skull seen from the front, two small dark holes on the forehead above its left eye circled in red."),
("2:35", DET+" He strikes a thinking pose, a thought bubble showing a tall shaft with a skull at the bottom."),
("2:40", "Cross-section of the shaft: bones and grey rocks tumbling down with motion lines."),
("2:45", "Layers of brown dirt pressing down on a white skull with black arrows, a small hourglass beside it."),
("2:50", DET+" He holds two signs: \"FALL?\" and \"SOMETHING ELSE?\"."),
("2:55", "A lab with a bone on a table, a scientist with a big magnifying glass, a sign on the wall \"FORENSICS\"."),
("3:00", "An old grey dry bone snapping into sharp straight pieces, next to a broken clay pot with the same straight cracks."),
("3:05", "A fresh white bone bending slightly before it cracks, with curved motion lines. A scientist pointing."),
("3:10", "Two twigs side by side: a green fresh twig bending, a brown dry twig snapping in two."),
("3:15", "The white skull with the two forehead holes, handwritten label \"FRESH FRACTURES\" and a green checkmark."),
("3:20", "The skull next to a calendar; a sign \"HEALED\" crossed out with a red X."),
("3:25", DET+" He takes off his hat sadly beside the skull on a table."),
("3:30", "Brown dirt layers pressing on a skull, crossed out with a big red X."),
("3:35", "A cartoon figure falling down the tall shaft with a big red question mark beside it."),
("3:40", DET+" He dramatically holds up a card reading \"CLUE 2\"."),
("3:45", "A boxy computer screen showing a green wireframe 3D skull with two holes, a scientist typing."),
("3:50", "The two holes drawn big side by side with a yellow ruler under them and a red equals sign."),
("3:55", "The outlines of the two holes overlapping and matching exactly, with the rounded end of a club fitting both."),
("4:00", "The skull with two red arrows coming in from two different angles into the two holes."),
("4:05", "A cartoon figure lying on the ground after a fall with one impact star; handwritten \"1 HIT\"."),
("4:10", "A figure falling with a single black arrow pointing straight down to one impact point."),
("4:15", "A grey rock with two red arrows at different angles and a big red question mark and red X."),
("4:20", NEA+" A caveman silhouette holding a wooden club over his shoulder, with curved motion lines and handwritten \"x2\"."),
("4:25", NEA+" The club swinging down with a cartoon \"BONK\" word and yellow impact star, no blood."),
("4:30", NEA+" The club raised again for a second swing, with \"BONK 2\"."),
("4:35", "A yellow banana peel and a sign \"ACCIDENT\" crossed out with a red X."),
("4:40", NEA+" Two cavemen in a cartoon dust-cloud scuffle, a sign \"ON PURPOSE\"."),
("4:45", DET+" He writes on a notepad titled \"KILLER PROFILE\", serious face."),
("4:50", "The skull seen from the front with a red arrow pointing to the forehead above its left eye."),
("4:55", NEA+" Two cavemen standing face to face in a cave, eyes locked."),
("5:00", NEA+" Close-up of two caveman faces nose to nose, one angry, one scared."),
("5:05", NEA+" A caveman holding a wooden club in his right hand, a curved red arrow showing the swing across his body."),
("5:10", "Top-down simple diagram of two figures facing each other; a red curved arrow from the attacker's right hand to the victim's left side."),
("5:15", DET+" He shrugs with a small red question mark while still writing."),
("5:20", "Close-up of the notepad with handwritten \"RIGHT-HANDED?\"."),
("5:25", "An evidence board with two impact stars, two figures facing each other and a red circle."),
("5:30", "An evidence table with a wooden club and a round grey stone, tags \"CLUB?\" and \"STONE?\"."),
("5:35", "A shadowy dark figure silhouette in a cave with a big red question mark, handwritten \"WHO? WHY?\"."),
("5:40", "Three thought bubbles over a cave: a piece of meat, a flag on a hill, a cracked heart."),
("5:45", DET+" He closes one folder and opens another, surprised."),
("5:50", DET+" He points at a chalk outline of a body on the cave floor with a question mark."),
("5:55", "Cross-section: a sunny green surface far above, a long dark tunnel down to a pit bottom with a small skull."),
("6:00", "A dark empty cave chamber; a cartoon brown bear shrugging with a red X beside it."),
("6:05", "Blue water drops crossed out with a red X, dry grey cave walls."),
("6:10", DET+" He scratches his head with a big red question mark."),
("6:15", NEA+" A small group of cavemen carrying a body wrapped in brown hide through a dark tunnel, sad faces."),
("6:20", NEA+" Cavemen at the edge of the shaft gently lowering a wrapped body down, sad faces."),
("6:25", "A simple world map of green blobs with a gold star on Spain and handwritten \"OLDEST?\"."),
("6:30", "Two panels with a red plus sign between: a raised club, and cavemen carrying a wrapped body."),
("6:35", "The skull with two holes and the outline of a club beside it."),
("6:40", NEA+" Cavemen carrying the wrapped body deeper into the cave, a red arrow pointing to the pit."),
("6:45", "Two big cartoon hands: one holding a club, one gently holding a wrapped body. Handwritten \"SAME HANDS?\"."),
("6:50", "A balance scale in a cave: a club on one side, a red heart on the other, perfectly level."),
("6:55", "The pink hand axe resting on white bones in the pit, a small red question mark."),
("7:00", NEA+" A caveman's hand gently placing the pink axe on the bones."),
("7:05", "The pink axe on the bones with a few small flowers beside it, handwritten \"GIFT?\"."),
("7:10", "A cartoon scientist in a white coat raising one finger, speech bubble \"CAREFUL\"."),
("7:15", "The shaft with bones sliding in from the side and several red question marks."),
("7:20", "Brown mud and blue water flowing through the cave, bones tumbling along."),
("7:25", "The pink axe next to a white dice showing six dots."),
("7:30", "The scientist shrugging with a small green checkmark."),
("7:35", "A balance scale: the side \"FUNERAL?\" light and high, the side \"MURDER\" heavy and low."),
("7:40", DET+" He looks confident beside the skull stamped in red \"CONFIRMED\"."),
("7:45", "The skull with two red arrows from two different directions."),
("7:50", NEA+" Two cavemen face to face in a cave, one raising a club, dramatic."),
("7:55", DET+" He points thoughtfully at a wooden sign \"WHY IT MATTERS\"."),
("8:00", SHA+" He waves in front of a cave."),
("8:05", SHA+" Two cavemen carry him on a stretcher made of brown sticks, all smiling."),
("8:10", "An open storybook on a table showing cavemen helping each other, a red heart."),
("8:15", "A big red heart with handwritten \"OLDEST\" and a green checkmark."),
("8:20", "The storybook with its pages split in half: one half a heart, the other half the Pit of Bones."),
("8:25", NEA+" Cavemen carrying an injured caveman through a dark cave, kind faces."),
("8:30", NEA+" Split frame: left, cavemen carrying an injured one; right, two cavemen face to face with a club."),
("8:35", "A timeline arrow with a heart and a club both drawn at the very start."),
("8:40", NEA+" One cave drawn with two scenes inside side by side: helping and fighting."),
("8:45", "A modern cartoon person in a living room pointing straight at the viewer."),
("8:50", "A modern person on an orange couch shaking their head, speech bubble \"NOT ME\"."),
("8:55", "A modern person with arms crossed watching a TV showing simple news icons."),
("9:00", "A family tree drawn as a brown tree: cavemen at the roots, a modern person at the top."),
("9:05", "The family tree with two roots: one caveman holding a club, one caveman carrying a body, both leading up to the modern person."),
("9:10", "A modern person with two small icons above their head: a blue shield and a wooden club."),
("9:15", "A blue shield and a wooden club both connected by arrows to one red heart."),
("9:20", "An X-ray style drawing of a skeleton on a lightbox with a red X, handwritten \"NOT IN THE BONES\"."),
("9:25", NEA+" A caveman at a fork in a dark cave path, signs \"RIGHT\" and \"WRONG\", handwritten \"CHOICE\"."),
("9:30", NEA+" The caveman walking down the WRONG path holding a club, toward a dark pit."),
("9:35", "Scientists in a lab piecing the skull back together, happy faces."),
("9:40", DET+" He closes the folder with a red stamp \"CASE CLOSED\"."),
("9:45", DET+" He holds a hand to his ear listening to the skull, which has a speech bubble."),
("9:50", DET+" He points at a new folder labelled \"NEXT CASE\"."),
("9:55", "A green rainforest with a cave in a limestone cliff, a sign \"BORNEO\"."),
("10:00", "A small smiling cartoon child with one leg and a brown crutch in front of the rainforest cave, a grey stone blade nearby, green checkmark."),
("10:05", DET+" He waves next to a big crude red rounded button with white handwritten text \"SUBSCRIBE\"."),
]
