# Frame list for "The First Dog Was a Terrible Idea". One frame per script timestamp.
# The recorded script restarts at 0:00 twice, so it's split into Part 1, Part 2 and Part 3.
STYLE = ("Medium-skill MS Paint sketch: a crude, rushed, hand-made doodle by someone with SOME drawing skill - amateur, funny, "
         "deliberately clumsy, beginner level. Simple cartoon stick-style characters: round heads, simple bodies and limbs, a little "
         "more shape than pure stick figures. Thick uneven wobbly black outlines, hand-drawn lines. Eyes as simple dots or plain "
         "circles, with simple clear facial expressions. Flat colour fills only in green, brown, grey, red, yellow, orange, blue. "
         "Fill the whole frame - no big empty white areas: give the background a flat-coloured sky or wall and ground plus a few "
         "simple doodled background details (a couple of trees, rocks, snowflakes, stars, a hill line) built from basic shapes. "
         "Red arrows or red question marks for emphasis where useful. NO shading, NO gradients, NO 3D, NO cinematic lighting, "
         "NOT polished, NOT Disney or anime, not vector art, not professional, no complex textures, no realistic people, not gory. "
         "Uncluttered and easy to read, subject centred with breathing room, nothing cropped, no broken anatomy, no stray extra "
         "details. Wide horizontal 16:9 YouTube video still. Any text is short handwritten scrawl, correctly spelled and legible.")

CAVE = "a stick-figure Ice Age person with scruffy brown hair and a simple brown fur tunic"
WOLF = "a crude grey wolf with pointy ears, bushy tail and yellow dot eyes"
DOG = "a crude friendly light-brown dog with one floppy ear, a wagging tail and a red collar"
CAMP = "Night Ice Age camp: dark blue sky with little white stars, white snowy ground, a crude orange campfire, a brown hide tent"

P1 = [
("0:00", f"{CAMP}. {CAVE} sits by the campfire, hands out to warm them, snowflakes falling. Handwritten label \"30,000 YRS AGO\"."),
("0:05", f"{CAMP}. Blue snowflakes everywhere, {CAVE} shivering beside a small pile of belongings: a spear, a basket, a rolled fur. Handwritten label \"WINTER\"."),
("0:09", f"{CAMP}. Three simple red arrows point at: a pile of brown meat, a stone axe and spear, and two small stick children asleep under a fur blanket behind the fire."),
("0:13", f"{CAMP}. At the edge of the firelight, the dark area beyond is black with many pairs of glowing yellow dot eyes. {CAVE} looks over nervously."),
("0:19", f"Snowy plain with a grey hill line and blue sky. Left: {CAVE} with a spear chasing a brown reindeer. Right: {WOLF} also chasing the same reindeer. Red arrows from both to the reindeer."),
("0:21", f"Close-up of {WOLF} with its mouth open showing white pointy teeth, snapping a white bone in half with a \"CRACK\" and little break lines. Snowy ground and a rock behind."),
("0:24", f"{WOLF} on a snowy hill at night with its nose up, wavy red smell lines drifting from a far-away meat pile. Its yellow eyes glow in the dark while a small stick person nearby squints with a question mark."),
("0:30", f"{CAMP}. {CAVE} stands up and tosses a red chunk of meat toward the dark where pairs of yellow eyes glow. Other stick people around the fire with shocked open-mouth faces."),
("0:36", "A crude yellow light bulb with a big red X over it, and a stick figure facepalming beside it. Handwritten text \"WORST IDEA\". Simple cave wall background in brown and grey."),
("0:39", f"A stick person holding a plate of meat out to {WOLF} whose plate is empty, and the wolf is eyeing the stick person's own plate. Red question mark. Snowy background with trees."),
("0:42", f"A crude brown wooden table with a candle in a cave, {CAVE} sitting on one side and {WOLF} sitting on the other side wearing a napkin, holding a fork. A red question mark over the person's head."),
("0:46", f"A crude round blue-and-green planet Earth covered in lots of tiny {DOG} doodles. Handwritten text \"900 MILLION\"."),
("0:50", f"A modern bedroom with a blue wall, a window and a lamp. {DOG} asleep curled up on a bed with little \"Z Z Z\" above it."),
("0:53", f"A modern stick person on a sofa scratching their head, looking at a thought bubble with {CAVE} throwing meat to {WOLF}. A red question mark."),
("0:59", f"A modern living room: {DOG} lying on a green couch. A red arrow points from a small {WOLF} doodle on the left to the dog on the couch. Handwritten text \"HOW?\"."),
("1:05", f"{DOG} doing silly tricks - sitting up, rolling over - with a big red X over it. A stick person shrugs. Park with grass and a tree behind."),
("1:08", "A brown dirt cross-section under green grass, with a white human skeleton and a small white dog skeleton lying side by side in it. A red arrow pointing to the dog skeleton."),
("1:10", "A crude old grey rock quarry with two stick-figure workers in flat caps holding pickaxes. Handwritten label \"1914\" on a wooden sign and \"GERMANY\"."),
("1:16", "The two stick-figure quarry workers leaning into a hole in the rock with wide circle eyes, a small white skull visible in the hole, a red exclamation mark."),
("1:18", "An open grave cross-section in brown dirt with three white skeletons: a man, a woman and a small dog, each with a red label arrow \"MAN\", \"WOMAN\", \"DOG\"."),
("1:22", "A timeline arrow on a stone wall with a red pin marked \"14,000 YRS\" and a small white dog skull above it. Brown ground and grey rocks."),
("1:26", "A dusty museum shelf with a small white dog skeleton in a box covered in grey cobwebs and a little spider, calendar pages flying past. Blue wall."),
("1:29", "A stick-figure scientist in a white coat with a big magnifying glass looking at a white dog jaw with teeth on a lab table, a yellow light bulb above their head. Green wall and shelves with jars."),
("1:33", "A sad little light-brown puppy lying on a fur blanket with a red thermometer in its mouth, sweat drops and a small sad face. Cave wall background."),
("1:36", "A crude green blob germ with angry dot eyes next to a sad little puppy. Handwritten label \"DISTEMPER\". Cave wall and fire in background."),
("1:41", "A shaky sick little puppy with wobbly shake lines, red thermometer, sweat drops, spinning dizzy stars above its head. Cave floor and wall."),
("1:44", f"Two small panels: left, a sick puppy lying down while a reindeer walks past, red X; right, a sick puppy lying down while {WOLF} sneaks past a camp, red X. Snow background."),
("1:47", "A sick puppy lying on a fur with a handwritten sign next to it reading \"USELESS\", then a big green checkmark with the word \"ALIVE\". Cave background."),
("1:50", "A wall calendar with lots of pages flying off, next to a sick puppy that is still breathing with little breath lines. Cave wall with a torch."),
("1:55", f"{CAVE} kneeling and hand-feeding a small sick puppy wrapped in a fur blanket beside a campfire, a small bowl of water nearby. Small red heart. Cave background."),
("2:00", f"{CAMP}. {CAVE} sitting up awake at night holding a sleeping sick puppy in their lap, a yellow crescent moon above, tired eye bags."),
("2:05", f"Inside a cold cave, {CAVE} holding a tiny piece of meat and splitting it in two: one half for themselves, one half for a small puppy. Nearly empty food basket. Snow outside the cave mouth."),
("2:07", "A brown dirt grave cross-section under snowy ground with white human skeletons and a small white dog skeleton lying close together, a small red heart above them."),
("2:11", f"{CAVE} hugging a small light-brown puppy, a big red heart above them. Cave wall and fire behind."),
("2:14", "A big red question mark in the middle of a grey cave wall, with a small stick person looking up at it confused."),
("2:16", "A crude green blob map with a red pin and handwritten label \"CZECH REPUBLIC\". A stick-figure archaeologist with a brown hat and shovel next to it."),
("2:21", "A brown dirt dig site with grid strings, a stick-figure archaeologist in a brown hat brushing a big white canine skull out of the ground. Handwritten label \"30,000 YRS\"."),
("2:25", f"A big white canine skull in the middle with a thought bubble showing {DOG}. A green checkmark. Background of grey rocks and dirt."),
("2:27", f"The same big white canine skull with a thought bubble showing {WOLF}. A green checkmark. Background of grey rocks and dirt."),
("2:29", "Two stick-figure scientists arguing across a table with a white canine skull between them, one speech bubble \"DOG!\" and the other \"WOLF!\". Lab wall background."),
("2:31", "A big white canine skull with a red circle drawn around its teeth and a red question mark. Dirt and rocks behind."),
("2:35", "Close-up of a white canine skull with a white bone piece stuck crosswise between its front teeth, a red arrow pointing to it. A small crude brown mammoth doodle in the corner."),
("2:38", "A stick-figure hand carefully placing a white bone between the teeth of a white canine skull lying on the ground. Snowy ground, trees behind."),
("2:41", "Side view of a white canine skull holding a bone in its teeth, with a dotted arrow leading off toward yellow stars in a dark blue sky."),
("2:44", "A white canine skull holding a bone, facing a crude glowing yellow doorway in a dark blue sky full of stars."),
("2:46", f"{WOLF} looking at a bone and a skull on the ground, shrugging with a confused face. A big red X over the scene. Snowy background."),
("2:48", f"{CAVE} standing proudly next to a white canine skull with a bone in its mouth, a green checkmark above. Cave background."),
("2:50", "A long timeline arrow pointing left across a brown ground, fading into grey dotted lines with a red question mark at the far left end."),
("2:53", "A crude yellow and green blob map with a red pin and handwritten label \"ISRAEL\". A small stone grave outline next to it and label \"12,000 YRS\"."),
("2:58", "A grave cross-section in brown dirt: an elderly white skeleton lying on its side, its bony hand resting gently on a small white puppy skeleton curled up next to it."),
("3:04", "A stick person throwing a small puppy doll into a hole carelessly, with a big red X over it. Brown ground and grass behind."),
("3:06", "Close-up of a white skeleton hand resting gently on a small white puppy skeleton, a red circle around the hand. Brown dirt background."),
("3:08", f"A modern bedroom at night: a stick person asleep in bed with one hand resting on {DOG} sleeping beside them. Window with moon."),
("3:10", "The grave with the elderly skeleton and the puppy skeleton touching, a small red heart above them, and grass and flowers growing on top."),
("3:14", f"A crude brown bird standing next to a grey cat and {WOLF}, none of them burying anything, with a red X above. Handwritten text \"ONLY US\". Grassy hill background."),
("3:16", f"{CAVE} tucking a fur blanket over a small sick grey wolf pup in a cave, a small red heart. A red arrow labelled \"PREDATOR\" pointing at the pup."),
("3:20", "A white skeleton hand resting on a small wolf pup skeleton under a starry blue night sky, a small infinity sign doodled above."),
("3:23", f"Left: {CAVE} holding a spear. Right: {WOLF} growling. Between them a jagged red lightning bolt that breaks apart into a small red heart. Snowy background."),
("3:28", f"A stick person scratching their head with a giant red question mark, looking at {CAVE} and {WOLF} standing together. Snowy trees background."),
("3:30", "A wrinkled paper plan on a wall showing a stick person and a wolf with a plus sign between them, crossed out with a big red X. Cave wall background."),
("3:33", "A stick person holding up one finger with a serious face, pointing at a sign reading \"PROBLEM\". Cave background."),
("3:34", f"A crude boxing ring on snowy ground: {CAVE} on one side, {WOLF} on the other, both glaring. Handwritten label \"RIVALS\"."),
("3:36", "A snowy plain with a herd of brown reindeer, brown horses and a big brown bison running. Blue sky and hills."),
("3:40", f"The same snowy plain seen wide: a line of stick hunters on the left and a pack of grey wolves on the right, both running toward the same herd of reindeer."),
("3:42", f"A pack of grey wolves eating a brown reindeer on the snow while {CAVE} stands nearby with an empty bowl and a sad face."),
("3:46", f"{WOLF} running with speed lines and a proud smile. Snowy hills."),
("3:47", f"{WOLF} zooming past with speed lines while {CAVE} runs behind panting with sweat drops. Then small inset: wolf teeth versus human teeth with a red arrow to the wolf."),
("3:49", "A pack of five grey wolves surrounding a huge brown moose on snowy ground, the moose looking worried. Pine trees behind."),
("3:53", "Two predators, a stick hunter and a grey wolf, both reaching for one single piece of meat on a rock between them. A red question mark. Snowy plain."),
("3:57", f"{WOLF} running away from {CAVE} who is waving a spear. A red arrow. Snowy hills."),
("4:00", f"{CAMP}. A thin hungry {CAVE} holding a small piece of meat, looking at the dark with glowing wolf eyes. A red question mark."),
("4:03", "A crude cave-painting style sign on a rock with a red question mark and a plate of meat. A stick person leaning in curiously."),
("4:06", "A stick person sitting in front of a huge pile of plain red lean meat, looking unhappy. A grey rock wall behind."),
("4:08", f"A thin wobbly stick person with a tired face, eating from a pile of lean meat, with a small red down arrow over them. Cave background."),
("4:14", "A crude white rabbit sitting next to a thin tired stick person. Handwritten text \"RABBIT STARVATION\". Grassy hill background."),
("4:16", "A stick person eating lots of meat while getting thinner and thinner in three small steps left to right, with a red down arrow."),
("4:19", f"{CAMP}. Deep snow piled high, icicles on the tent, a stick person looking at a big pile of red meat with a puzzled face."),
("4:23", "A stick hunter team next to a brown mammoth or bison outline, red arrows pointing to: a yellow blob labelled \"FAT\", a white bone labelled \"MARROW\", and a red heart shape labelled \"ORGANS\"."),
("4:26", "A big leftover pile of plain red lean meat by a hide tent in the snow, a stick person with a full round belly waving it away."),
("4:30", f"{WOLF} looking at the pile of lean meat and licking its lips with a big grin and a green checkmark. Snowy background."),
("4:32", f"{WOLF} eating lean meat happily, with a small calendar next to it showing \"MONTHS\" and a green checkmark. Snowy trees."),
("4:35", "A stick-figure scientist in a white coat pointing at a chalkboard showing a drawing of a meat pile with an arrow to a wolf. Green chalkboard, lab wall."),
("4:38", f"{CAMP}. {CAVE} tosses leftover lean meat to {WOLF}; a price tag reading \"FREE\" hangs on the meat."),
("4:42", "A split meat pile: fatty yellow parts with an arrow to a stick person, plain red lean meat with an arrow to a grey wolf. Snowy camp background."),
("4:45", f"{CAVE} dumping a basket of scraps, {WOLF} eating them. A crossed-out red heart and a handwritten label \"LEFTOVERS\"."),
("4:49", "Two stick-figure scientists standing by a chalkboard, one pointing at a different diagram. A red question mark. Lab wall background."),
("4:51", f"{WOLF} sneaking up at night to a pile of garbage bones and scraps behind a hide tent, digging through it. Stars and snow."),
("4:56", "Two stick-figure scientists arguing with speech bubbles, one says \"INVITED!\", the other says \"TRASH!\". A lab wall and table."),
("4:59", f"{CAVE} and {WOLF} shaking hand and paw over a crude paper contract, a handwritten label \"THE DEAL\". Campfire behind."),
("5:02", f"{WOLF} with a red X over a pet bed and a toy ball. Snowy camp background."),
("5:03", f"{WOLF} sitting at the edge of firelight eating a thrown-away bone, with a handwritten label \"NOT A PET\". {CAMP}."),
]

P2 = [
("0:00", f"{CAMP}. {WOLF} creeping very close to the fire to grab a bone from a scrap pile, while {CAVE} watches it warily. A red warning triangle."),
("0:10", f"{CAMP}. A circle of grey wolves hanging back in the dark with glowing yellow eyes, and one smaller wolf stepping forward into the firelight with a curious face. A red arrow points to it."),
("0:29", "A small cave den with a grey mother wolf and three tiny grey pups, one of the pups smiling and looking toward a distant campfire. Snow and trees."),
("0:42", "A stick-figure scientist with glasses picking one calm, smiling orange fox out of a row of cages while the other foxes snarl angrily. A green checkmark above the calm fox. Farm fence and barn behind."),
("0:55", "An orange fox wagging its tail with motion lines and licking a stick person's hand. A small red heart. A farm with wire fences and a barn behind."),
("1:18", "Side-by-side: left, a wild orange fox with pointy ears and an angry face; right arrow; a spotted white and orange fox with floppy ears, curly tail and a happy face. Handwritten \"10 GENERATIONS\"."),
("1:29", "A timeline arrow stretching far to the left across snowy ground, with a grey wolf on the far left slowly turning into a brown dog on the right in three steps. Handwritten \"1000s OF YRS\"."),
("1:38", f"Big close-up of {DOG} doing sad puppy eyes: huge round eyes and lifted inner eyebrows. A red arrow points at the eyebrows. A living room behind."),
("1:46", "A stick-figure scientist in a white coat with a magnifying glass looking at a crude diagram of a dog face and a wolf face, a small red muscle shape above the dog's eye circled in red. Handwritten \"2019\"."),
("1:56", f"{DOG} doing puppy eyes at a modern stick person who is holding out a treat with a helpless smile. A red heart. Kitchen background."),
("2:03", f"A modern stick person trying to say no to {DOG} with puppy eyes, then giving in and handing over a sausage. Kitchen background."),
("2:08", f"A modern stick person and {DOG} staring into each other's eyes with dotted lines between their eyes, little pink hearts floating up. Living room."),
("2:17", "A crude map blob labelled \"JAPAN\" with a red pin, and a stick-figure scientist holding a chart with a line going up and a red heart."),
("2:25", f"A modern stick person staring at {WOLF} while the wolf looks away, bored, with a flat line chart and a red X. Lab room background."),
("2:34", "A modern stick person pointing across a living room at a ball on the floor, a red arrow following the pointing direction."),
("2:43", f"Left: a chimpanzee with a confused face and a red question mark staring at a pointing hand. Middle: {WOLF} staring at the hand itself. Right: a small puppy looking at the ball where the hand points, with a green checkmark."),
("2:53", f"A big red arrow looping from {WOLF} to {DOG}, and then a second arrow looping from a stick caveman to a modern stick person. Handwritten text \"BOTH CHANGED\"."),
("3:00", f"{CAMP}. Dogs lying around the fire among a group of stick people, one child petting a dog. Busy friendly camp."),
("3:09", f"A snowy forest hunt: {CAVE} walking with a spear and {DOG} walking beside them sniffing the ground. Pine trees, blue sky."),
("3:18", "A crude human nose labelled \"6 MILLION\" next to a much bigger crude dog nose labelled \"300 MILLION\". Red arrow pointing to the dog nose."),
("3:29", f"A hunt: {DOG} barking and cornering a brown deer against rocks, while {CAVE} runs up from behind with a spear. Snowy trees."),
("3:35", "A crude yellow blob map with a red pin and handwritten label \"SAUDI ARABIA\". A tall brown sandstone rock with simple carved-looking stick figures on it."),
("3:43", "A flat brown rock face with simple rock-art doodles: a stick hunter holding a bow, surrounded by several stick dogs, one with a thin line from its neck to the hunter's waist. Desert sand and a yellow sun."),
("3:52", "A close-up of the rock carving: the thin leash line from a dog's neck to the hunter's waist circled in red, with handwritten text \"LEASH\"."),
("3:59", f"{CAMP}. Stick people asleep in the tent while {DOG} stands guard, ears up, barking at dark shapes of a bear and lion hiding behind trees."),
("4:11", "A stick-figure scientist pointing at a chalkboard with a stick person plus a wolf equals a trophy. A lab wall."),
("4:22", f"A snowy plain: a group of stick hunters with dogs (on the left) moving forward confidently while a short stocky heavy-browed stick Neanderthal (on the right) looks worried. A red question mark over the Neanderthal."),
("4:29", "A stick scientist with a speech bubble \"MAYBE!\" and three other stick scientists with arms crossed and speech bubbles \"NOPE\". Lab background."),
("4:36", f"{CAVE} and {DOG} standing side by side as one team, with a plus sign between them and a green checkmark. A campfire behind."),
("4:44", f"A lonely skinny {WOLF} in a snowy forest looking at a distant warm camp with dogs and people. A red arrow."),
("4:49", "A crude round Earth with only a few tiny grey wolves scattered on it. Handwritten text \"250,000\"."),
("5:01", f"{WOLF} hiding in the dark of a forest with a red X, while in the distance {DOG} sits happily by a campfire with people."),
("5:11", f"A crude round Earth covered in lots of tiny {DOG} doodles on every continent. Handwritten text \"900 MILLION\"."),
]

P3 = [
("0:00", f"A modern bedroom: {DOG} asleep on a bed, a bowl of kibble on the floor. A small inset of a wolf with a green checkmark next to the word \"WINNER\"."),
("0:28", f"{CAMP}. {CAVE} gently throwing a piece of meat toward a single {WOLF} stepping out of the dark into the firelight."),
("0:43", f"A modern living room: {DOG} tilting its head at a modern stick person who is talking, a small red heart between them. Faded campfire doodle in the background."),
("0:57", f"A modern stick person sitting on a couch with {DOG} resting its head on their lap. A small red heart above. Behind them, a faded outline of a wolf by a campfire. Handwritten \"TRUST\"."),
]
