# One frame per transcript timestamp for "The First War in Human History" (Jebel Sahaba).
import json
STYLE = ("Medium-skill MS Paint sketch: a crude hand-made doodle by someone with some drawing skill - amateur, funny, "
         "deliberately clumsy. Characters are simple cartoon stick-style people with round heads and simple bodies, eyes as "
         "plain dots or circles, and clear simple facial expressions. Thick uneven hand-drawn black outlines. Flat colour fills "
         "only (green, brown, grey, red, yellow, orange, blue). The whole frame is filled with NO empty white space: a simple "
         "flat-coloured background built from primitive shapes (river, sand, sky, reeds, rocks, ground, room walls, shelves) with a "
         "few simple background details, but no complex textures. Red arrows or red question marks for emphasis. NO shading, NO "
         "gradients, NO 3D, NO cinematic lighting. NOT a polished cartoon, NOT Disney or anime look, not vector art, not "
         "professional, no realistic people. Not gory, no blood. Uncluttered, subject centred with breathing room, nothing "
         "cropped. Wide horizontal 16:9 YouTube video still. Any text is short handwritten scrawl, correctly spelled and legible.")
DET = "The DETECTIVE is a cartoon stick-style man in a brown trench coat and brown hat, holding a magnifying glass."
NILE = "The river people are simple cartoon figures with brown skin, short dark hair and plain tan cloth wraps."
SHA = ("The SHANIDAR MAN is a cartoon Neanderthal with a heavy brow, scruffy brown hair, his left eye drawn as a small x, "
       "his right arm ending in a short stump, leaning on a brown walking stick.")
ARC = "A cartoon archaeologist in a khaki shirt and wide brown hat."

P1 = [
NILE+" A family asleep on reed mats beside a dark blue river at night, yellow crescent moon and stars, tall reeds. Handwritten \"13,400 YEARS AGO\".",
NILE+" A sleeping family on open sand by the river at night. Three small icons crossed out in red: a wall, a door, a guard.",
NILE+" Close view of a mother, father and child sleeping peacefully by the river at night, little blue water ripple lines.",
NILE+" One person sits up wide awake in the dark, scared circle eyes. Behind the reeds, several dark shadowy figures and footprints. Red exclamation mark.",
NILE+" Morning by the river, orange sunrise. A small group stands sadly beside empty reed mats where others used to sleep.",
NILE+" A sad person by the river holding a wall calendar full of red X marks.",
NILE+" The same calendar with an arrow pointing to more future pages, the person looking worried. Handwritten \"AGAIN\".",
ARC+" Two archaeologists digging in sand on the bank of the blue Nile, palm trees, finding the tops of graves.",
"A sandy cross-section with many graves side by side under the ground, the Nile flowing above. A red circular arrow meaning again and again.",
NILE+" Two groups of cartoon people on either side of a river facing each other with spears, angry faces. A red question mark.",
NILE+" Two groups clash in a cartoon dust cloud with spears and little arrows flying, no blood, with red circular arrows around them.",
"A wooden sign on a sandy riverbank reading \"THE FIRST WAR\", with spears crossed beneath it.",
"A timeline arrow on a brown wall: far left a small red crossed-spears icon, then to the right a green field of wheat. Red arrow points at the spears.",
"The timeline continues: crossed spears on the far left, then wheat, then a little grey city icon, then a small yellow crown on the far right. A cartoon person looking surprised.",
"A cartoon person smiling with a small yellow sun rising behind them and a green checkmark, handwritten \"HOPE?\".",
DET+" He sits in his office opening a brown folder labelled \"OLD CASES\".",
SHA+" He waves in front of a cave.",
SHA+" Close portrait with red arrows pointing at his x eye and his arm stump.",
SHA+" Two cavemen carry him on a stretcher made of brown sticks, everyone smiling.",
"A dark cave pit full of white bones with a wooden sign \"PIT OF BONES\".",
"A white skull with two holes on its forehead circled in red, a sign \"430,000 YRS\".",
"Two stocky cavemen standing face to face in a grey cave, one raising a wooden club. Handwritten \"x2\".",
DET+" He holds up one finger next to a sign \"1 KILLING = CRIME\".",
"Three small panels: one cartoon person, one clock, and a fork in a road with a red X on one path.",
DET+" He points dramatically at a big sign \"WAR\".",
NILE+" One whole group of people on the left angrily pointing at another whole group on the right across a river. Red arrow.",
"A chalkboard with three ticked boxes: \"PLANNED\", \"REPEATED\", \"PASSED DOWN\".",
NILE+" A family tree on a wall: grandparents and parents each holding a spear, all looking the same direction.",
NILE+" A young person at the bottom of the family tree now holding a spear, looking unsure.",
DET+" He scratches his head with a big red question mark.",
"A wooden signpost with an arrow labelled \"ANSWER\" pointing to a green farm field.",
"A green farm field with rows of crops, a tiny farmhouse, and handwritten \"FARMING\".",
"A cartoon farmer standing on a field holding a pitchfork, a little fence, a red arrow pointing at the field.",
"A grey city wall on the left and a cartoon king with a yellow crown giving orders on the right.",
"A wide blue river in Sudan with blue water rising up the sandy banks, rising arrows. Handwritten \"SUDAN\".",
"A wall calendar showing \"1960s\" pinned in a planning office with a map on the wall.",
"A huge grey concrete dam across the blue Nile, cartoon construction cranes, sign \"ASWAN HIGH DAM\".",
"The finished dam with a lake building up behind it.",
"Side view: a big blue lake spreading behind the dam over a valley, red arrows showing the water spreading.",
"Small ancient ruins and pyramids in the valley with blue water creeping toward them, red question mark.",
ARC+" Several archaeologists from different places running with shovels and buckets toward the valley.",
ARC+" Archaeologists digging fast in sand while a blue wave of water approaches in the background, sweat drops.",
"A racetrack with an archaeologist running on one lane and a blue water wave on the other, finish line flag.",
ARC+" An archaeologist with a moustache holding a clipboard, sign \"1965\", standing on desert sand by the river.",
"A simple map with two blobs labelled \"EGYPT\" and \"SUDAN\" and a dotted border line, a red pin on the border by a blue river.",
"A wooden sign stuck in the sand reading \"JEBEL SAHABA\", the blue Nile and a small rocky hill behind.",
ARC+" Archaeologists brushing dry sand away to uncover the outline of a grave near the river.",
"Loose white bones scattered on sand crossed out with a red X.",
"A neat sandy cemetery with rows of graves side by side, each outlined, a small red heart.",
"A sandy cross-section of a grave showing a white skeleton lying on its side with its knees pulled up.",
"A grave pit covered with flat grey stone slabs, cross-section showing the skeleton beneath.",
"A sandy cross-section with two skeletons lying side by side in the same grave.",
"A cemetery map with many small grave outlines and handwritten \"61\" with small icons of a man, a woman and a child.",
ARC+" Two archaeologists shrugging next to an ordinary-looking grave, handwritten \"NORMAL?\".",
ARC+" An archaeologist leaning in with a big magnifying glass over a white bone on a table, surprised face.",
"A white bone on a table with tiny grey stone chips scattered everywhere around it, red arrows.",
"Brown dirt with a red X over it, the stone chips not in the dirt.",
"Close-up of a white bone with a small grey stone chip stuck inside it, red circle.",
"A white rib bone with a small grey stone flake lodged in it, red arrow.",
"Four small panels: a hip bone, a spine, and a skull, each with a tiny grey stone flake stuck in it.",
"Simple cartoon stone-tipped arrows and a spear with grey stone tips on a sandy ground, red arrows pointing at the tips.",
"A cartoon arrow flying through the air with motion lines toward a target bone shape, no blood.",
"Diagram: an arrow tip snapping off inside a bone, the stone tip staying inside, red circle.",
"The bone with the stone tip inside, next to an hourglass and handwritten \"13,000 YEARS\".",
"A male skeleton outline with a small stone chip marked in red, and a red arrow pointing onward.",
"A female skeleton outline with a stone chip marked in red.",
"A small child skeleton outline with a stone chip marked in red, a sad red question mark.",
"An old brown book titled \"JEBEL SAHABA\" lying open on a desk.",
NILE+" Inside the book: a drawing of one big battle by the river, labelled \"ONE DAY?\".",
NILE+" Sad cartoon people burying the dead together after the battle in sandy graves.",
"A wall calendar showing \"2021\" and a group of cartoon researchers in white coats walking toward boxes of bones.",
"A grand museum building with columns and a sign \"BRITISH MUSEUM\", boxes of bones inside.",
"A lab with a microscope and a computer screen showing a bone, a researcher looking through the microscope.",
"A bone on a table with a ruler measuring it centimetre by centimetre, small red tick marks.",
"A researcher in a white coat with a shocked open-O mouth and a red exclamation mark, staring at a bone.",
"A white bone with a smooth healed lump where it was once damaged, a green checkmark, handwritten \"HEALED\".",
DET+" He strikes a thinking pose with a thought bubble showing a healed bone.",
"A healed bone with a green checkmark next to a small smiling stick figure, handwritten \"SURVIVED\".",
"A bone with a crack slowly filling in over three panels, with a calendar showing weeks passing.",
NILE+" A person by the river being hit by a small arrow with a cartoon impact star, no blood.",
NILE+" The same person later with a bandage, recovered, then shadowy figures approaching again, red circular arrow.",
NILE+" Sad family members by a fresh grave by the river.",
NILE+" An old person with visible scar lines on their arm, lying peacefully in a grave.",
"A chart on a wall with many red dots on skeleton drawings, a researcher pointing at it, handwritten \"MISSED\".",
"One skeleton with two kinds of marks: a green healed mark and a red new mark side by side.",
"The same skeleton with a red circle around both marks, handwritten \"SAME PERSON\".",
"A row of skeleton outlines, most of them marked with small red dots.",
"A sign \"ONE BATTLE\" crossed out with a red X.",
NILE+" Shadowy raiders sneaking through the reeds toward a sleeping camp, a red dotted path.",
NILE+" Small fight scenes by the river repeating along a timeline with red circular arrows.",
NILE+" A family tree with several generations, each generation with a small crossed-spears icon.",
"A circle diagram labelled \"WAY OF LIFE\" with spears and a river drawn inside it.",
"A farm field crossed out with a red X.",
"Three icons crossed out with red X: a field, a city, a crown.",
NILE+" Cartoon people fishing in the blue Nile with spears and nets from the bank.",
NILE+" Cartoon people hunting an animal with spears on sandy grassland, and others gathering wild plants into baskets.",
]
P2 = [
DET+" He scratches his head with a big red question mark beside the river.",
"A globe with a melting blue ice cap and a wobbly thermometer swinging up and down.",
"A split frame: left side cracked brown dry ground and a hot sun, right side a flooded blue river over its banks.",
"A riverbank with a few good spots marked by fish, water and animals, the spots shrinking with red inward arrows.",
NILE+" Two groups of people looking at a small pile of fish, eyeing each other suspiciously.",
NILE+" One group sees the other group drawn as scary red shadow monsters, a red exclamation mark.",
NILE+" Two groups pushing and shoving over a small patch of green land by the river.",
"A scientist in a white coat in a lab raising one finger, speech bubble \"CAREFUL\".",
NILE+" A hunter tripping during a hunt with a cartoon \"OOPS\" and a little star, an antelope running away.",
"A long timeline with grave icons spread out far apart along it.",
"A trophy labelled \"FIRST?\" with a red question mark, and a shovel digging in the ground next to it.",
"A gold medal labelled \"OLDEST FOUND\" next to a small hole in the ground with a red question mark.",
DET+" He holds up a skeleton drawing with red marks, pointing at it.",
"Several skeleton outlines of different sizes, each with a small stone chip marked in red.",
"A timeline with repeating crossed-spears icons, all to the left of a small farm icon at the far right.",
DET+" He points at a wooden sign \"WHY IT MATTERS\".",
"A grand building with columns, gold coins and a crown, and a red question mark over \"WAR CAME FROM THIS?\".",
"A peaceful daydream bubble of cartoon people and animals living happily by a river, the bubble popping with a red X, a wooden sign \"JEBEL SAHABA\".",
NILE+" Three icons crossed out in red at the top: gold coins, an empire flag, a crown. Below them two groups still face off with spears by the river.",
DET+" He stands in the sandy cemetery holding up one finger next to a sign \"ONE MORE CLUE\".",
"A sandy cemetery with neat graves covered by flat grey stone slabs, a small red heart.",
"Cross-section of two skeletons lying side by side in the same grave; at the edge a cartoon hyena crossed out with a red X.",
NILE+" People gently covering a grave with flat stone slabs, kind sad faces.",
NILE+" People standing together around the graves holding hands, while far in the background tiny shadowy raiders lurk.",
"A modern cartoon person in a living room pointing straight at the viewer.",
"A modern person sleeping peacefully in a cozy bed with a blue blanket, a locked door and a yellow moon in the window.",
"A simple bar chart on a wall with a tall red bar labelled \"THEN\" and a short green bar labelled \"NOW\".",
"A modern person shrugging next to a sign \"PEACE = NATURAL?\" crossed out with a red X.",
"A long staircase climbing upward with cartoon people building each step, handwritten \"CHOICES\".",
NILE+" Two groups trading baskets of fish and fruit instead of fighting, smiling faces, a small courthouse and a scroll of laws in the background.",
"Old bones in the sand by the blue Nile with a small red crossed-spears icon and handwritten \"WAR IS ANCIENT\".",
"Cartoon people holding up a big green dove sign labelled \"PEACE: INVENTED\", smiling.",
"A modern person on an orange couch with a thought bubble showing the Nile cemetery.",
"A balance scale with crossed spears on one side and a red heart beside a grave on the other, perfectly level.",
"A modern person standing at a fork in the road: one sign shows crossed spears, the other sign shows a red heart.",
"A green rainforest with a dark cave in a grey limestone cliff, a wooden sign \"BORNEO\".",
DET+" He waves next to a big crude red rounded button with white handwritten text \"SUBSCRIBE\", and a small picture on the wall of a smiling child on a crutch.",
]
segs = json.load(open("segments.json"))
SCENES = [(p, ts, txt, s) for (p, ts, txt), s in zip(segs, P1 + P2)]
assert len(P1) == sum(1 for s in segs if s[0] == 1) and len(P2) == sum(1 for s in segs if s[0] == 2), (len(P1), len(P2))
